#ifndef CARINFOTAINMENTSYSTEM_FW_APP_INCLUDE_SETTINGSPROVIDER_H
#define CARINFOTAINMENTSYSTEM_FW_APP_INCLUDE_SETTINGSPROVIDER_H

class SettingsProvider {
  public:
    bool init() const noexcept { return true; }
};

#endif    // CARINFOTAINMENTSYSTEM_FW_APP_INCLUDE_SETTINGSPROVIDER_H
