#ifndef CARCLOCK_FW_TARGETS_APP_INCLUDE_TEMPERATUREPROVIDER_HPP
#define CARCLOCK_FW_TARGETS_APP_INCLUDE_TEMPERATUREPROVIDER_HPP

class TemperatureProvider {
  public:
    bool init() const noexcept { return true; }
};

#endif    // CARINFOTAINMENTSYSTEM_FW_APP_INCLUDE_TEMPERATUREPROVIDER_H
