#ifndef CARINFOTAINMENTSYSTEM_FW_APP_INCLUDE_TEMPERATUREPROVIDER_H
#define CARINFOTAINMENTSYSTEM_FW_APP_INCLUDE_TEMPERATUREPROVIDER_H

class TemperatureProvider {
  public:
    bool init() const noexcept { return true; }
};

#endif    // CARINFOTAINMENTSYSTEM_FW_APP_INCLUDE_TEMPERATUREPROVIDER_H
